# To build the images
# docker-compose build

# To run the containers
# docker-compose up

# Which version of the docker-compose API to use
version: '2'

services:

  # api server container
  go-facts-api:
    container_name: go-facts-api
    build: ./go-facts-api
    volumes:
      - ./go-facts-api:/go-facts-api
    ports:
      - 8080:8080 

  # client app webserver
  go-facts-webserver:
    container_name: go-facts-webserver
    build: ./go-facts-webserver
    volumes: 
      - ./go-facts-webserver/html:/usr/share/nginx/html
      - ./go-facts-webserver/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
